### ISSUE TITLE
Добавить в ветку develop файлы из ветки teamwork-23-cohort блоки, начиная с search и заканчивая uploader

### ISSUE THREAD

**Issue by LatyshevDD** [LatyshevDD/ProCharity#35]

**Comment by shaman365** [comment]
Изменения лежат в ветке fix/css-search-uploader-23-cohort.

У 23 когорты на компоненте Статус профиля (.sidebar__status) курсор меняется на 'cursor: help'. Я не нашёл такого требования в макете, вернул на 'cursor: pointer'
