### ISSUE TITLE
Исправить расположение кнопки закрытия попапа на странице регистрации НКО "Контакты"

### ISSUE THREAD

**Issue by LatyshevDD** [LatyshevDD/ProCharity#80]
![Image](https://github.com/LatyshevDD/ProCharity/assets/110352990/d478ff1b-48ae-4c07-ab0a-9a761982ac25)

**Comment by IvannaBalanyuk** [comment]
Вроде бы в develop-team-1 сейчас всё ок с кнопкой закрытия попапа:
![image](https://github.com/LatyshevDD/ProCharity/assets/124444858/fb591d01-af83-4e12-a0de-ead9cd7a9347)
